version: '3.1'
services:
  web:
          #build:
          #context: ./docker
    image: wilfreedo/cakephp3
    container_name: 'test'
    volumes:
      - ./html/app:/var/www/html
      - ./change-apache-user.sh:/usr/local/bin/change-apache-user.sh  
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/webroot
    ports:
      - "8080:80"
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file:
      - apache.env
    command: /usr/local/bin/change-apache-user.sh    
  db:
    image: mariadb
    container_name: 'test-db'
    restart: always
    volumes:
      - db-test:/var/lib/mysql
    env_file:
      - db.env
volumes:
  db-test:      
